### ISSUE TITLE
Recipe feature

### ISSUE THREAD

**Issue by collegeStudent35632** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#16]
allowing users to save recipes with their preferred ingredients as well as allowing them to save those meals so they can be re-used at a later date.

**Comment by Vanasbry000** [comment]
1. Need to have users, sign in page, log in page, change password, authentication
2. need to have recipe table in the database
3. need to have meal table in the database which are assigned to users that create them

**Comment by a-xia** [comment]
Closing because we have more specific issues for this now.
