### ISSUE TITLE
Navigation bar update

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#208]
**REGARDLESS:**

**1.** Logo linking to homepage _{% url 'nutrihacker:index' %}_
**2.** Search bar (via a form)

**IF NOT LOGGED IN:**

- [x] Login _{% url 'nutrihacker:login' %}_
- [x] Register _{% url 'nutrihacker:register_account' %}_

**IF LOGGED IN:**

- [x] My Logs _{% url 'nutrihacker:log_list' %}_
         a.  New Log _{% url 'nutrihacker:log_create' %}_
         b.  Today's Log _(not yet implemented, might not implement, would possibly only appear in the expando in the case of there already being a daily log for the current day)_
- [x] My Recipes _{% url 'nutrihacker:list_recipe' %}_
        a.  New Recipe _{% url 'nutrihacker:create_recipe' %}_
- [x] Profile _{% url 'nutrihacker:profile' %}_
         a.  Diet and Allergies _{% url 'nutrihacker:diet_and_allergies' %}_
         b.  Update Profile _{% url 'nutrihacker:update_profile' %}_
         c.  Change Password _{% url 'nutrihacker:change_password' %}_
- [x] Logout _{% url 'nutrihacker:logout' %}_

**Comment by collegeStudent35632** [comment]
#227
