### ISSUE TITLE
Reworking the organization and header of the website

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#39]
Homepage needs to be changed.
Search bar could be at the header of every page on the site for convenient use.
"Foods" link in the header doesn't need to be there.
"About Us"is useless right now, perhaps remove it?
"How it Works" describes the prototype requirements, will it be renovated in our final version or do we remove it?
Add link at the top for login/register

**Comment by Tsion-Tadesse** [comment]
"About Us"is useless right now, perhaps remove it? Replaced "About us" by "login/register"
Removed Food

**Comment by Tsion-Tadesse** [comment]
Added the search bar in "How It Works" page, so it's pretty much in every page.
