### ISSUE TITLE
Change app name from prototype to something else, updating all references to it

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#66]
If you have any ideas for names, comment them here!

**Comment by Vanasbry000** [comment]
* Nutrihelper
* Digital Nutritionist
* Food Tracker
* Trackhacker

**Comment by a-xia** [comment]
Nutrihacker?

**Comment by Vanasbry000** [comment]
Renaming the project folder from nutrihelper to project
Renaming the app folder from prototype to nutrihacker
