### ISSUE TITLE
Create daily log and related models

### ISSUE THREAD

**Issue by a-xia** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#73]
**Sub tasks:**
- [x] Daily log components:
    - [x] User field (many to one)
    - [x] Date field
    - [x] Function to calculate total nutrition information
- [x] Meal log components:
    - [x] Date and time field
    - [x] Daily log field (many to one)
- [x] Meal food components:
    - [x] Meal log field (many to one)
    - [x] Food field (many to one)
    - [x] Portions field

**Test cases:**
- [x] Daily log, meal log, and meal food can be created from admin page
- [x] Food can be added to meal foods, meal foods can be added to meal logs, and meal logs can be added to daily logs in admin page
- [x] Function to calculate total nutrition information can be run from shell and is correct

**Comment by sjiang1** [comment]
Are all the tasks due Oct. 12? If so, please update it in the epic. 

Other than that, it looks good.
