### ISSUE TITLE
Task: Create and implement recipe models

### ISSUE THREAD

**Issue by Vanasbry000** [COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper#75]
- [x]  User can create and save recipes with multiple foods
- [x]  Recipes are specific to user and they have any number of foods and portions of each food

Recipe data model
- [x] Many to One with users

RecipeFood data model
- [x] Many to One with Recipe
- [x] Many to One with foods
- [x] Has a portion attribute

User can save recipes
- [x] User interface of adding foods
- [x] User interface to save recipes
- [x] Functionality of saving recipes
- [x] Portions are remembered

TEST CASES:
- User can create and save recipes with multiple foods
- Recipes are specific to user and they have any number of foods and portions of each food

**Comment by Vanasbry000** [comment]
PLANNED DATABASE STRUCTURE FOR RECIPES AND RELATED MODELS:

Meal data model
- [ ] Many to One with users
- [ ] Has a timestamp attribute

MealRecipe data model
- [ ] Many to One with Meal
- [ ] Many to One with Recipe
- [ ] Has a portion attribute with units like “3 lasagnas”

MealFood data model
- [ ] Many to One with Meal
- [ ] Many to One with Food
- [ ] Has a portion attribute

Recipe data model
- [ ] Many to One with users

RecipeFood data model
- [ ] Many to One with Recipe
- [ ] Many to One with foods
- [ ] Has a portion attribute

**Comment by sjiang1** [comment]
Are the following items your test cases for the issue?
> User can create and save recipes with multiple foods
> Recipes are specific to user and they have any number of foods and portions of each food

**Comment by Vanasbry000** [comment]
Yes, those are my test cases, thank you for following up. I've since placed them in here for clarity
